### ISSUE TITLE
Add cave height setter

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#109]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A min and max value for cave height limits

**Additional context**
I need flat caves to not always spawn on y=5 or 6 or 4

**Comment by cyberpwnn** [comment]
You dont need this, you should use the vertical slope in json such as

```json
{
    "verticalSlope": {
        "max": 64,
        "min": 16,
        "generator": {
            "style": "PERLIN_IRIS",
            "zoom": 8
        }
    }
}
```

Just zoom your noise a bit. Also, its not possible to do that because of how the caves generate. Iris has to check a lot to see if caves are even possible at a Y level (optimization). Adding that kind of height check would slow iris caves down by up to 300%
