### ISSUE TITLE
Iris World Creation Issue(s)

### ISSUE THREAD

**Issue by TheModdersDen** [VolmitSoftware/Iris#1119]
## Hello!

I have an issue (similar to that of issue #654), but with a bit of a twist: I have the same issue (or at least a VERY similar one) on the paid and purchased version of Iris and at least 2 self-compiled builds.

### The Issue

Based on what's in the linked log, it appears that, when generating the world, Iris crashes the server. Minecraft has updated **A LOT** since I've last looked at its source code (modded and programmed plugins for it), so I could be entirely wrong. But that's my guess, based on my history and experience with the game.

In addition, in order to (hopefully) help speed up the efforts to diagnose and troubleshoot this, I will include a (mostly) comprehensive list as to what I've tried to amend/remedy the issue on my end, this far:

- [Restarted my server](https://www.youtube.com/watch?v=t2F1rFmyQmY)
- Re-downloaded and replaced Iris with a fresh copy from SpigotMC (where I bought it, full price-$20-to support y'all 😄)
- Deleted/backed up and re-generated **all** world/dimensional files
- Compiled a copy, locally, using the information gleaned from this repository and the aforementioned issue (included the `shadowJar` task, to attempt to fix it.
- Tried to compile v4.0, but was met with an unfamiliar error.

I will keep this issue as 'up-to-date' as possible, should any solution arise.

Looking forward to a reply,
//TheModdersDen

### Solution

I think it has to do something with Issue #654, but I'm not entirely sure.
(See the main issue for more details)

### Minecraft Version

1.21 (Purpur 1.21.1 v2329)

### Iris Version

v3.4.3

### Log

https://mclo.gs/H6CmNuZ

**Comment by NextdoorPsycho** [comment]
Thank you!On Nov 5, 2024, at 21:21, Bryan Hunter ***@***.***> wrote:﻿
Problem
Hello!
I have an issue (similar to that of issue #654), but with a bit of a twist: I have the same issue (or at least a VERY similar one) on the paid and purchased version of Iris and at least 2 self-compiled builds.
The Issue
Based on what's in the linked log, it appears that, when generating the world, Iris crashes the server. Minecraft has updated A LOT since I've last looked at its source code (modded and programmed plugins for it), so I could be entirely wrong. But that's my guess, based on my history and experience with the game.
In addition, in order to (hopefully) help speed up the efforts to diagnose and troubleshoot this, I will include a (mostly) comprehensive list as to what I've tried to amend/remedy the issue on my end, this far:

Restarted my server
Re-downloaded and replaced Iris with a fresh copy from SpigotMC (where I bought it, full price-$20-to support y'all 😄)
Deleted/backed up and re-generated all world/dimensional files
Compiled a copy, locally, using the information gleaned from this repository and the aforementioned issue (included the shadowJar task, to attempt to fix it.
Tried to compile v4.0, but was met with an unfamiliar error.

I will keep this issue as 'up-to-date' as possible, should any solution arise.
Looking forward to a reply,
//TheModdersDen
Solution
I think it has to do something with Issue #654, but I'm not entirely sure.
(See the main issue for more details)
Minecraft Version
1.21
Iris Version
v3.4.3
Log
https://mclo.gs/H6CmNuZ

**Comment by TheModdersDen** [comment]
You're welcome.

Also, I couldn't find a valid link to the Volmit Discord. Is this intentional? The one listed on your site header didn't work (invalid invite) along with the one from the aforementioned issue.

Thanks again!

**Comment by NextdoorPsycho** [comment]
Should be working on spigot. Can you send me a screenshot or a link to where it’s busted?Join the Volmit Software Discord Server!discord.ggOn Nov 5, 2024, at 22:25, Bryan Hunter ***@***.***> wrote:﻿
You're welcome.
Also, I couldn't find a valid link to the Volmit Discord. Is this intentional? The one listed on your site header didn't work (invalid invite) along with the one from the aforementioned issue.
Thanks again!

**Comment by TheModdersDen** [comment]
Hrmmmm... I don't know what else I could link or screenshot outside of what I've already sent (mainly just due to the fact that my server won't start up fully so I can't get a full plugin list using `/plugins`, etc...)

If there's anything else that's feasibly helpful I would be glad to send it. I'm just going to need some more specifics other than "screenshot or link to where it's busted" as I don't really know where it's busted.

If you're referring to the discord invite, the one I tried using was the one in your website (https://www.volmit.com). Specifically the one in the menu/header.

😅😁😇

**Comment by TheModdersDen** [comment]
Update: it would appear as if I fell victim to the good ol' error code 27C.

Turns out that I missed a step when compiling it myself and another plugin was causing issues as well. I will be closing this issue as resolved until further notice.

Thanks again for the kind words, patience, and support! 😃
