### ISSUE TITLE
Add spawn check for structures / objects to make sure they're on a certain type of block

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#138]
**Is your feature request related to a problem? Please describe.**
Potentially fixes the objects-spawning-on-void issue, but that's not the main reason for this request.

**Describe the solution you'd like**
Add a check (just like the height clamping) for structures and objects to make sure they spawn on a block type of choice, i.e.: having a biome with grass blocks and coarse dirt and only wanting to have some structure / object spawn on the grass and not on the coarse dirt.

**Describe alternatives you've considered**
Making separate biomes for them, which is more work especially when you want to change something in both of them (or when you get 3 or 4 block types)

**Comment by cyberpwnn** [comment]
This would be horrendously expensive on the cpu. Iris objects place into a virtual region. This is why you can have massive objects touching without cascading chunk gen.

The solution here im assuming is to make objects not place if the terrain is carved away. This is less expensive and iris does this to a certain degree. Try lowering the fluid height? Perhaps that might be causing it to give up at the bottom.

Either way, this wont be an issue when v2 comes out because of slivers.

**Comment by svdgoor** [comment]
I'm looking for a configuration option which would allow me to check what block the structures is attempted to be placed on. I understand this would be CPU intensive but I think it would be a nice feature to have nonetheless.

I'll consider making this again when V2 releases to see if there's still a necessity
