### ISSUE TITLE
Always spawning in the same biome despite different seeds

### ISSUE THREAD

**Issue by CocoTheOwner** [VolmitSoftware/Iris#207]
**Describe the bug**
Regardless of a seed, you (in the current version) always spawn in a tundra-mountains biome. In the previous version it was an ocean.

**To Reproduce**
1. Make and teleport to any overworld-pack-created world with an yseed
2. Run /ir w b to find you're in the tundra-mountains biome

**Expected behavior**
Seeds strongly impact the biome you spawn in.

**Server and Plugin Informations**
 - Installed plugins: Nothing that matters
 - Iris Version: 1.1.5
 - Server Platform and Version [eg: PaperSpigot 1.16.3 #240]: Latest paper
 - Operating System (if applicable): win10 64x

**Comment by svdgoor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Unaffected by seed](https://trello.com/c/99iAzAlR/6-unaffected-by-seed)

**Comment by MassiveLag** [comment]
Same thing

**Comment by ghost** [comment]
Is linked to multiverse. Wont happen when using the bukkit.yml method. Should be obsolete with the mca and jigsaw system.

**Comment by MeGunes** [comment]
Fix please

**Comment by Frerduro** [comment]
> Fix please

This is being fixed you just need to be patient.

**Comment by ghost** [comment]
I tested this with bukkit.yml and multiverse method (thou I changed the regions order so it’s not default) and you spawn in different regions/biomes. If I’m wrong pls reopen this.

**Comment by svdgoor** [comment]
Cantibra's report:

---------------


Describe the bug
There is maybe a bug in the seed system. Each pre-generated world contains the same structure despite a different seed.

As an an example:
- /ir create <worldname> type=overworld seed=443733762757695 pregen=2048
- /ir create <worldname> type=overworld seed=-650906254974921 pregen=2048

= ends in the same world with exactly the same structure.

To Reproduce
Steps to reproduce the behavior:
- /ir create <worldname> type=overworld seed=<seed> pregen=2048

Expected behavior
Worlds generated differently depending on the seed

Screenshots or Video Recordings
/

Server and Plugin Informations
 - Installed plugins: Iris
 - Iris Version: 1.2.5
 - Server Platform and Version [eg: PaperSpigot 1.16.3 VolmitSoftware/Iris#240]: PaperSpigot 1.16.4 #394
 - Operating System (if applicable): MacOS 11.1
 - Server Logs: /

**Comment by svdgoor** [comment]
The same thing does not happen when using the bukkit.yml method where the seed is saved in the level.dat and rerolled when that file is deleted.

**Comment by MeGunes** [comment]
Please fix this. @cyberpwnn

**Comment by ghost** [comment]
Is fixed by using either bukkit.yml method or multiverse method PLUS rearranging the regions inside of the dimension file (to get a different spawn biome).

For the bukkit.yml method you need to specify the seed in the properties file
For the multiverse method you specify the seed by using /iris create <yourworldname> seed=<yourseed>

**Comment by MeGunes** [comment]
No, I tried it and this method doesn't work. Please don't just close this anymore. This is an issue that needs to be fixed.

**Comment by svdgoor** [comment]
He has tested this on the latest version with Multiverse and with the Bukkit method. If neither of those are working for you, please try removing the level.dat file or moving the names of the different regions in the dimension file like he also suggested. If none of those work, let me know and I will test it myself and conclude it then.

**Comment by ghost** [comment]
I can support and help you with your issue on discord. I think it’s a misconfiguration and therefor you‘re running into that issue

**Comment by svdgoor** [comment]
![image](https://user-images.githubusercontent.com/65736624/104932519-00ef6980-59a8-11eb-99b8-ee0cc35db2fb.png)
![image](https://user-images.githubusercontent.com/65736624/104932538-06e54a80-59a8-11eb-83c5-af80077598fa.png)
[latest.log](https://github.com/VolmitSoftware/Iris/files/5831008/latest.log)
As confirmation that this is actually resolved.

**Comment by svdgoor** [comment]
(/ir create world2 seed=1
/ir create world3 seed=20000)
