### ISSUE TITLE
Terrain should not take priority over objects

### ISSUE THREAD

**Issue by Astrashh** [VolmitSoftware/Iris#215]
**Describe the bug**
Currently any terrain that overlaps with blocks a part of objects will take priority, meaning that objects partially submerged in the ground gets overwritten.

**Expected behavior**
I would expect objects to take priority over terrain, seeing as it wouldn't make sense for things like houses to be gobbled by terrain, and as a result of the current behavior - things like basements, subterranean objects, etc all aren't possible.

**Additional feature**
In addition, it would be nice to be able to toggle whether objects or terrain gets placed, on a per object basis

Will provide more info later when I can.

**Comment by Frerduro** [comment]
TBH I think this should be a feature request not a bug report.

**Comment by astrsh** [comment]
Whether or not its intended I don't know - but I guess it's both a bug and feature request depending on that. 

Anyway - here's an example of the terrain taking precedence over objects. I've outlined in red where there is stone instead of the gold blocks from the object.

![image](https://user-images.githubusercontent.com/73215501/102703532-18153b80-42c4-11eb-9b92-5637de509063.png)

Here is another example of a hut that is partially submerged into the terrain
![image](https://user-images.githubusercontent.com/73215501/102703600-ec468580-42c4-11eb-9ed2-7408035044b4.png)

The same as above but with the blocks broken by hand
![image](https://user-images.githubusercontent.com/73215501/102703634-6d9e1800-42c5-11eb-86aa-bf38f6160e6c.png)

This is the original object, you can see in the above image that none of the furniture spawned, because the terrain has overwritten it.
![image](https://user-images.githubusercontent.com/73215501/102703612-1f891480-42c5-11eb-8831-4bb5b3dd2ee5.png)

**Comment by RaydenKonig** [comment]
This seems to me quite important because not only would it help the houses not to be overwritten, but it would open the possibility to create underground dungeons whose entrance is on the surface

**Comment by svdgoor** [comment]
For sure a bug. Behaviour changed with V2 gen. This is a bug report for making objects default overwrite terrain and a feature request for a setting that reverts that back to the current (buggy) method where terrain gets priority over objects.

**Comment by svdgoor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Terrain priority over objects](https://trello.com/c/XePSXYhG/4-terrain-priority-over-objects)

**Comment by cyberpwnn** [comment]
Turn on smart bore in the object, and fill the air with cobweb, this will force air in the objects. This is how we do it with some of the structures with crops in them. It also overrides any other structures too. But objects do overwrite terrain, But an object wont place air unless you explicitly tell it to (with either bore or smart bore)

**Comment by svdgoor** [comment]
![image](https://user-images.githubusercontent.com/65736624/106358555-37fd3d80-630d-11eb-8376-5bc6adad5aad.png)
            "place": ["test1"],
            "chance": 0.5,
            "bore": true,
            "boarExtendMaxY": 10,
            "boarExtendMinY": 10,
            "translate": {
                "y": -5
            },
Works like a charm.
Same for smartbore, works slightly differently but does what you want it to do.

![image](https://user-images.githubusercontent.com/65736624/106358583-70048080-630d-11eb-90fc-e8d3bace6ee5.png)

these are the same ones but without bore turned on (only thing is "bore": false)
Replaced sand and sandstone and found the structure's blocks are placed properly.
