### ISSUE TITLE
SpawnerCreature takes 60% of my ticks

### ISSUE THREAD

**Issue by KoxSosen** [VolmitSoftware/Iris#216]
**Describe the bug**
With 200 players, and nearly 36k loaded chunks, for some reason the SpawnerCreature.spawn.mobs takes 60% of my ticks, brining my tps down to 2. Cpu usage is at 30%, htop system load is 3.

**To Reproduce**
1. Pregenerate a 5k world using iris.
2. Get 200 players/bots moving on the same world.
3. Take a spark

**Expected behavior**
This even sould not eat 60% of all ticks.

**Screenshots or Video Recordings**

https://spark.lucko.me/#wtmQQdJdgw

**Server and Plugin Informations**
 - Iris Version: 1.1.6
 - Paper 1.16.4 latest

**Additional context**
- None

**Comment by Frerduro** [comment]
I have looked at both the spark and timings and I don't see how this is an iris issue. Have you tried changing your entity limits?

**Comment by KoxSosen** [comment]
https://spark.lucko.me/#GLk9xtoBHl

Spark without Iris. 

There's 201 bots walking around in a vanilla 2500x2500 world, almos stable 18-20 tps now.

**Comment by KoxSosen** [comment]
With Iris, I have 2 tps with the same seed, same bots. There's something wrong here.

**Comment by svdgoor** [comment]
I understand why you would say this is Iris' issue but it is not.
I think the issue lies with a spawner that is tracking the bots to find the closest player. Iris does not affect spawner behaviour at all.

According to the spark log, the reason for the lag is a calculation for getting the distance between the player and the spawner (I presume to calculate spawnrates). I think that there may be an issue with one or more plugins in your server where (what I think is) the bots are recognised or at least counted as players by the spawners, which makes the distance check happen extremely often and basically freezing the server.

Again, this does not have anything to do with Iris as we do not affect spawners.

If you can reproduce this issue without having bots we will re-open this thread and investigate further.

**Comment by KoxSosen** [comment]
Hm, that's really strange. Without iris the issue does not accour, but I can test with players as well. I would like to mention that the bots are created using a .js program called Mineflayer, and the game has 0 idea they are bots, they do the same as a player would do

**Comment by svdgoor** [comment]
It may be a combination of both Iris and Mineflayer, but I still have a hard time seeing how Iris plays any role in this.
