### ISSUE TITLE
A couple new command ideas?

### ISSUE THREAD

**Issue by AZFire1** [VolmitSoftware/Iris#294]
**Is your feature request related to a problem? Please describe.**
No, it is not related to a problem. These are just some ideas I had which I thought I'd go ahead and suggest. 

**Describe the solution you'd like**
The new commands I had in mind were "/ir what structure" and "/ir what object".  These are some self-explanatory commands which would tell you the name of what object/structure you are looking at.

**Comment by svdgoor** [comment]
It what object is included in the Dust of Revelation which you can get with /ir obj dust.

Ir what structure will not be implemented as it is suitable to find which object the specific part of the structure is. Then you can check out which jigsaw structure(s) use(s) that object since you should and hopefully have placed the objects in folders based on what jigsaw structure they are is (make sure to name jigsaw structures, pieces, pools and objects such that they are logically ordered so you don't lose track of what's up)

I can automatically reroute the /ir what object command into the dust command, would that be useful?

**Comment by AZFire1** [comment]
Sure, that could work if you rerouted the dust command when executing "/ir what object".
