### ISSUE TITLE
Noise Cellular 

### ISSUE THREAD

**Issue by RaydenKonig** [VolmitSoftware/Iris#339]
**Describe the error**
"Cellular" noise and all its variants suffers from a very notable error

This consists of creating completely straight lines by cutting the biomes in an unnatural and very ugly way.

and currently, this noise is the only one that allows a random distribution of biomes more in line with minecraft vanilla

**To Reproduce**
1. Go to '/ standard iris noise'
2. Click on 'cell phone'
4. and pay attention to the straight lines that are created
5. another way to see it is at http://188.40.189.134:8080/
and pay attention to the biomes in the world "dunya"

**Expected behavior**
noise should provide a smoother and visually appealing transition of biomes

**Screenshots or video recordings**
here is an example using a color dimension to test noise
![2021-03-20_13 56 23](https://user-images.githubusercontent.com/71474946/113185629-0e896100-922d-11eb-9997-153a1f8f9eb0.png)
![2021-03-20_14 06 24](https://user-images.githubusercontent.com/71474946/113185650-1517d880-922d-11eb-8809-147c5a03e834.png)

**Server information and plugins**
 - this happens in all irises regardless of the server

**Additional context**
I think that this error should be a priority to solve it since it significantly affects the generation of the world and the distribution of its biomas

Another option would be to add a new, different noise that has a great variety of colors, since "cellular" noise is not the most attractive visually.

**Comment by astrsh** [comment]
This would have to do with domain warping (aka fracturing), not with cellular. It just happens to be more apparent with cellular as its one of the only styles that has harsh diagonal transitions that line up with the diagonal bias (which results from an incorrect domain warp implementation).

**Comment by cyberpwnn** [comment]
Cellular noise uses v zoom which means you have a grid of "pixels" that are blown up using nearest neighbor. The reason it doesnt look like polygons everywhere is because iris is fracturing it as @Astrashh  mentioned. You can hide this better with more fracturing but it's a performance cost. We need another noise gen to solve this artifact. This cannot be solved with cellular though. 

Iris uses a really odd way of fracturing though, it only uses one generator to reduce noise hits (how many times we call a noise gen per chunk). There is an option in the config i believe called accurate fracturing or something. It might actually be on the generator json itself. Turning that on will fix your issue, but it will drop performance a fair bit if you use it everywhere.
