### ISSUE TITLE
The Infinite Pit

### ISSUE THREAD

**Issue by NextdoorPsycho** [VolmitSoftware/Iris#352]
**The infinite Pit**
Pits, like actual holes in the world in the mushroom overworld

**To Reproduce**
1. Go to the mushroom forest and look at the terrain amidst the trees

**Expected behavior**
Not doing that

**Screenshots or Video Recordings**
https://i.imgur.com/q6pO91T.jpg
https://i.imgur.com/3ShMueT.jpg
https://i.imgur.com/nBO4ZgP.jpg

**Other Info**
- Its always the same Width
- Not chunk dependent
- Not unique to mushroom Biome, it just happened a bit more frequently there

**Comment by svdgoor** [comment]
Feature

**Comment by StrangeOne101** [comment]
I think these could perhaps be caused by errors in noise generation. The reason being that the Height is 0 and the Slope is NaN, and Minecraft had a similar bug in the past. Seen here: https://minecraft.fandom.com/wiki/Java_Edition_removed_features#Monoliths

All that is mentioned as of writing on it was `By setting "Biome Scale Weight" to negative values in old customized worlds`, but I don't know how it relates to Iris biomes as of yet. 

I've also noticed it mostly in Ice biomes. I suspect that certain (Iris) generators used within certain biomes cause this while others seem immune to the problem. That's probably why it's so hard to track down

![](https://i.imgur.com/TgBZRSu.png)

**Comment by svdgoor** [comment]
Fixed
