### ISSUE TITLE
Failed to generate 

### ISSUE THREAD

**Issue by B1gLev** [VolmitSoftware/Iris#356]
**Describe the bug**
Failed to generate and exception  

**Expected behavior**
With the new version and older versions, after a while, errors occur during generation which can also be seen in the log, the consequence of which is that after a while the server crashes. 

**Server and Plugin Informations**
 - Installed plugins: 
![image](https://user-images.githubusercontent.com/40140251/119176430-63966600-ba6b-11eb-893e-c0ad418db8f9.png)

 - Iris Version:  Iris version 1.3.1
 - Server Platform and Version Purpur version git-Purpur-1118 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 7 version(s) behind
Previous version: git-Purpur-1047 (MC: 1.16.5)
 - Operating System (if applicable): 

**Additional context** 
[2021-05-21-3.log.gz](https://github.com/VolmitSoftware/Iris/files/6524180/2021-05-21-3.log.gz)

**Comment by svdgoor** [comment]
Good that you created this. Seems like an outdated or broken library to me. Dont know how it's intertwined with the rest of the generation and even less so how to replace the library and with what. But that's what Cyber is for :)

**Comment by B1gLev** [comment]
It is interesting, and another server we use 1.3.1 on a very old paper version and there is no such error there. If the plugin is running on a newer paper version then this error came up and the server crashed after a while. So I don’t know what to do with this, because these freezes are very unpleasant for the players.  
However, this also happened with the newer version of Iris

And what is cyber?

**Comment by svdgoor** [comment]
Who* is cyber.
It's Cyberpwn, the main dev of the plugin.
And yeah, it seems paper is changing world gen stuff that breaks our code apparently.

**Comment by B1gLev** [comment]
Ooh okay
And when is the update expected in this regard? Or is it still hopeless for a while?

**Comment by ghost** [comment]
> Ooh okay
> And when is the update expected in this regard? Or is it still hopeless for a while?

„Hopeless“ for now. The dev (Cyber) has a lot to do and nobody (except him) knows when and on what he will work

**Comment by NextdoorPsycho** [comment]
Turn your server into online mode, What java version are you using?

**Comment by B1gLev** [comment]
> Turn your server into online mode, What java version are you using?

Version 16

**Comment by cyberpwnn** [comment]
`java.lang.NoClassDefFoundError: Could not initialize class io.timeandspace.smoothie.SmoothieMap` What? So basically a class no def error means that the server (purpur) is using smoothie maps but a different version, and Iris is calling for another version... however because (im assuming) Purpur has already classloaded its own smoothie maps, Iris's maps arent getting loaded and instead deferring to the purpur ones, BUT while this would normally be fine, i guess SmoothieMap classes were significantly changed over the versions, hence the classnodeffound

Or.... i could be overthinking this and what is really happening is the Iris Jar does not contain smoothie map classes at all (build issue). 

Do me a favor @B1gLev ... Open that iris jar with WinRar and look for `io/timeandspace/smoothie/` If that exists in the jar than its the first issue. Otherwise if its missing its the second issue.

**Comment by B1gLev** [comment]
Yes it is 
![image](https://user-images.githubusercontent.com/40140251/119656750-55f62d00-be2b-11eb-9acb-fa1005e8096e.png)

**Comment by cyberpwnn** [comment]
Hmmm so i need to dep match or use an isolated classloader. Alright i know how to fix it.

**Comment by ethrx** [comment]
Anyone know if using an older build of purpur/paper would work or would we have to use an older version of Iris. I've tried multiple paper/purpur builds so I'm assuming we will just have to wait for the issue to be fixed by @cyberpwnn  ?

Thanks

**Comment by StrangeOne101** [comment]
This should be fixed now. Java 16 support has been added and smoothie maps have been removed from use. Either 1.3.11-FINAL or 1.4.-EXPERIMENTAL should have fixed this

**Comment by NextdoorPsycho** [comment]
Fixed on latest
