### ISSUE TITLE
Thoughts on how to handle pack updates

### ISSUE THREAD

**Issue by espen96** [VolmitSoftware/Iris#359]
The general idea is that if you have information that tells you how a chunk was created(versioning and using old packs etc.) You can use that data to extrapolate between the old chunks and new ones, filling in the gap. 

This would work especially well with minor tweaks to a pack.
And even if it might sometimes get a bit funky, I think it could still help a lot. 

I do think that mojang will have to do something similar for the caves and cliffs part two update, so it might be worth thinking about ways to do something like that.

If the concept is even worth humoring I'll probably keep updating this with various ideas as to how to approach this issue. 

I am fully aware that it's a big thing to add, and I don't expect it to be worked on at all, but it never hurts to share thoughts and ideas imo.

**Comment by cyberpwnn** [comment]
Its not a big thing to add, its a cpu intensive thing to add. Small or large differences take about the same amount of cpu. For example, if in plains for example... you increase tall grass by 50%, and run this "retrogen", 

1. Where are plains biomes? (we need to run the biome map to find this out)
2. Cant decorate unless we know the height map... so might as well generate the terrain too
3. We cant know where the grass is (because decorations need to know what block they can / cant place on... so might generate surface layers too

My point is you have to regenerate the chunk even if the changes are super small. Even if iris was redesigned, it wouldnt be easy to make a system that can change things specifically without being instanced... and im pretty sure that would drastically increase memory usage.

**Comment by cyberpwnn** [comment]
My only idea would be a way for iris to simply be able to regenerate chunks preferably through the pregen system

**Comment by espen96** [comment]
What would regenerating the chunk do other than making that old chunk match the new pack rather than the old?  
The idea here is to smooth the transition from old chunks to new chunks, not modify old ones.

**Comment by ghost** [comment]
> What would regenerating the chunk do other than making that old chunk match the new pack rather than the old?
> The idea here is to smooth the transition from old chunks to new chunks, not modify old ones.

You should read the first message too

**Comment by espen96** [comment]
Ah, my bad, complete brain fry there. 
Yeah, I see what you mean now
