### ISSUE TITLE
Shutdown error

### ISSUE THREAD

**Issue by ghost** [VolmitSoftware/Iris#412]
**Describe the bug**
Error messages that appear during manual shutdown. (No crash)

**To Reproduce**
1. Startup
2. Shutdown

**Expected behavior**
/

**Screenshots or Video Recordings**
/

**Server and Plugin Informations**
 - Installed plugins: ArmedArmorStands*, ChatManager, Chunky, CommandToItem, DiscordSRV, DualWield*, floodgate, Geyser-Spigot, Harbor, HolographicDisplays, Home, Iris, LiveKit, LuckPerms, LWVG*, ProtocolLib, SepareWorldItems, ShulkerPacks, SimplePortals, SuperVanish, TAB, UltraRegions, Vault
 - Iris Version: 1.4.14
 - Server Platform and Version: git-Paper-103 (MC: 1.17.1)
 - Operating System: Linux Debian Buster - Open-JDK 16
 - Server Logs: [pastebin.com/H4i0PT7w](https://pastebin.com/H4i0PT7w)

**Additional context**
/

**Comment by svdgoor** [comment]
Have this too

**Comment by cyberpwnn** [comment]
Yeah really odd, normally if the server crashes it will dump logs, otherwise, someone is using Bukkit.getServer().stop() or whatever it is. Iris doesnt do this, so im not sure why it could be happening while iris is installed. It also looks like it happens a couple minutes after the server has started. Could it be your control panel or something? Maybe a failing auto-restart?

**Comment by svdgoor** [comment]
This is not a crash, @cyberpwnn, it's actually just an error on shutdown.

**Comment by cyberpwnn** [comment]
> This is not a crash, @cyberpwnn, it's actually just an error on shutdown.

Was referring to the actual cause of the shutdown

**Comment by ghost** [comment]
> > This is not a crash, @cyberpwnn, it's actually just an error on shutdown.
> 
> Was referring to the actual cause of the shutdown

It as a manual shutdown

**Comment by svdgoor** [comment]
Haven't seen the issue on shutdown in a good long time. Reopen if it resurfaces.
