### ISSUE TITLE
Constant crashing in pregenerated world with custom pack

### ISSUE THREAD

**Issue by p3sto** [VolmitSoftware/Iris#483]
### Problem

N/A

### Minecraft Version

1.17.x

### Iris Version

1.5.12

### Log

https://mclo.gs/wsOmBjC

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](discord.gg/volmit))

**Comment by p3sto** [comment]
Found the issue in my pack but is there a way to perhaps add some exception handling

**Comment by ArMiN231** [comment]
> Found the issue in my pack but is there a way to perhaps add some exception handling

https://docs.volmit.com/iris/plugin/faq#how-do-i-prevent-unimportant-papermc-warning-spam

**Comment by svdgoor** [comment]
No, @ArMiN231 this is a real problem.
Iris is capable of doing some stuff with entity spawns, but it's overriding its own events.
If you look at the stacktrace at the bottom, it's just repeating itself

**Comment by p3sto** [comment]
Is this solved?

**Comment by svdgoor** [comment]
Cyber did know about it but I don't know for sure

**Comment by svdgoor** [comment]
com.MobFarmManager.Zrips.Listeners.EntityListener.onCreatureSpawnEvent(EntityListener.java:63) 

Likely due to incompatibility with this plugin.
We're doing everything properly afaik, and that plugin is just recursively calling Iris' spawn events on the Iris world.
Perhaps you can consider contacting the plugin developers for a patch, use another plugin, or come back here if those options are exhausted.
