### ISSUE TITLE
Safe RAM limitation in pregeneration option

### ISSUE THREAD

**Issue by StrangeOne101** [VolmitSoftware/Iris#490]
### Adding, Removing, or Changing

Adding

### Type of Modification

A boolean setting in the config

### What are you trying to modify

A setting for pregeneration to only use 90% of allocated RAM. This is for servers who are managed by something like pterodactyl which will halt the server if it detects all the RAM being used.

```json
"generator": {
    "safePregeneratorRAM": true
}
```
The setting would default to false though. More RAM = better for 90% of customers

### Alternatives

They just not use pterodactyl lol

**Comment by NextdoorPsycho** [comment]
java -Xms6500M -Xmx6500M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs/ -Daikars.new.flags=true -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar


Just use the flags from aikar, thats the solution that the server hosts use, and it world, because ram is not the issue, they are preventing the user from virtualizing threads when above 50% ram (according to a server host)
