### ISSUE TITLE
Frozen Mobs Underground

### ISSUE THREAD

**Issue by StrangeOne101** [VolmitSoftware/Iris#607]
### Problem

Mobs are spawning underground, but do not die, rise to the surface, or do anything.

I assume this is a bug with the rising mob feature of Iris

Edit: The mob spawns WAY too deep underground, rises, does not make it to the surface, then stops.
Edit 2: I wonder if this is related to #605. Since the height they SHOULD spawn at is completely different to the ones they do spawn at

![2021-09-04_22 05 58](https://user-images.githubusercontent.com/2769013/132090794-6fec8ebe-6e99-49e2-9289-0664b3fd8aa9.png)

Alternatively, mobs will just die underground.
![2021-09-04_22 07 39](https://user-images.githubusercontent.com/2769013/132090882-42f2706f-0828-4967-9df6-1ef800c88c43.png)

### Minecraft Version

1.17.x

### Iris Version

1.8.3

### Log

.

### Checklist

- [X] I am using an unmodified version of Iris. (If you modified the plugin and see an issue, make sure it is reproducable on the latest spigot version or contact [support](https://discord.gg/volmit))
- [X] I am using Spigot, Paper, Tuinity, or Purpur. (If you are not, and still think it is a valid issue, contact [support](https://discord.gg/volmit))

**Comment by cyberpwnn** [comment]
So this one is a little weird... here's some insight though. Basically
1. If the mob is too far away from a player, teleporting the mob (as a plugin) wont actually move the entity
2. Previously iris would continue moving up the entity until it wasnt underground.

The issue was mobs far away were not moving and forever-teleporting up but not actually moving positions. So the tps would tank because all these mobs are rapidly ticking but not actually moving. I prevent this (now) by having a cut-off time where essentially if its been more than 60 ticks, Iris gives up and stops ticking it. I think what needs to be done here is... when Iris gives up, teleport it to the top.... that being said the entity may not teleport up so I'm not sure how to deal with this. 

Possibly I could tighten the range that the effect actually plays and if it's outside the range of any player it just spawns like normal.

**Comment by StrangeOne101** [comment]
Perhaps in the meantime, add an option to the config that disables the underground spawning behaviour

**Comment by ghost** [comment]
Closing #587 cause this is a better report
