### ISSUE TITLE
Iris occur many lag - BlockBreakEvent

### ISSUE THREAD

**Issue by IPECTER** [VolmitSoftware/Iris#619]
### Problem

1. Iris World Gen 1.8.7
2. Just using Iris 1.8.7 with overworld pack
3. playing server with 4 player
4. Iris occured lag 
5. run pregen radius 1000
6. but look timing report.. iris engine occured lag

### Solution

before optimizing Server and with many peaple
https://timings.aikar.co/?id=5d920ba2c2f443678789ee571c3c5809#timings

### Minecraft Version

1.17.1

### Iris Version

1.8.7

### Log

https://mclo.gs/B9x6P2D

**Comment by svdgoor** [comment]
Hey!

I have tried reproducing your issue but did not manage to.
I notice you say there are four players on the server while you are pregenerating, this is not a good idea. There should not be anybody on the server at the time you're pregenerating because of the connection between main server thread instability and pregeneration issues.
You can expect the server to be less responsive during pregeneration. What I see in your timings reports are sporadic events of lag, which are caused by pregeneration, and can be expected.
