### ISSUE TITLE
Error while pre-generation after /remove command

### ISSUE THREAD

**Issue by winstonvanderpol** [VolmitSoftware/Iris#626]
### Problem

1. Start Pre-Gen
2. Write /remove items 50
3. Receive constant error after each pre-generation console log

### Minecraft Version

1.17.1

### Iris Version

1.8.7

### Log

https://mclo.gs/V986Hs5

**Comment by svdgoor** [comment]
Please do not run any commands during pregen
Please leave the server empty during pregen
These are not errors, they are warnings generated by paperMC because the server is unresponsive. This is caused by the small amount of pressure your command causes while iris is using up almost all computing power.
You can use that command after pregen is done. The issue with items being left on the floor and in caves should be resolved on the next version.

Please come by Discord first the next time, we reply there more quickly and will point you here when there is an issue that isn't easily solvable.

Thank you for taking the time to report this!
