### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by kireevm96** [VolmitSoftware/Iris#674]
### Problem

The map is regenerated in advance by a 30k radius. When more than 30 players are online, a lack of memory is noticed. The server was allocated 30 GB. After increasing the memory to 80 GB. this allowed 80 players to enter. When disabling iris, the server consumes no more than 6 GB of memory. Different kernels were tried, the problem with the iris remained.
If necessary, I can provide a memory dump.
https://cdn.discordapp.com/attachments/768582615078010910/893540715471200276/unknown.png

### Minecraft Version

1.17.1

### Iris Version

1.9

**Comment by kireevm96** [comment]
One instance of «com.volmit.iris.engine.IrisEngine» loaded by «org.bukkit.plugin.java.PluginClassLoader @ 0x7f01980d89a8» occupies 10 237 804 704 (74,97 %) bytes. The memory is accumulated in one instance of «java.util.concurrent.ConcurrentHashMap$Node[]», loaded by «<system class loader>», which occupies 10 237 531 072 (74,97 %) bytes.

**Comment by kireevm96** [comment]
https://disk.yandex.ru/d/Hn47lFGhqpyp6g dump

**Comment by Cenoic** [comment]
+++ 30k radius pregen - Same issue, running at 12GB with 6 players online running Iris and only 5GB with 6+ online without Iris.  Can create a new heapdump and provide hprof if requested (as we've already deleted the original hprof file, but you do have the hprof seen above.

https://www.dropbox.com/s/wr04fjo690ntp97/heap-2021-10-27_10.37.12_Leak_Suspects.zip?dl=0

![image](https://user-images.githubusercontent.com/92695286/139306369-c319c4bb-9ed1-4991-81cc-1fadd7d01b22.png)
![image](https://user-images.githubusercontent.com/92695286/139306419-8a6755fb-3e05-4c68-bebb-5882f9b4c2ac.png)
![image](https://user-images.githubusercontent.com/92695286/139306446-4054d32c-abc7-4f4d-9485-92202798ccaf.png)

**Comment by Cenoic** [comment]
-> Heapdump is obviously run with the rest of the plugins enabled, I disabled to isolate the ram usage to Iris, as the only player online (in a separate world not using Iris) I proceeded to get a sawtooth MEM pattern (Typically consistent with a memory leak)

I ran the server without Iris with no trouble, no random spikes, no crashes, no sawtooth pattern.

**Comment by cyberpwnn** [comment]
Thank you for the dump... Now to figure out which map is misbehaving. Might be a hash issue.

**Comment by Cenoic** [comment]
Hprof dump


https://www.dropbox.com/s/xoi9554j2ja3lz9/heap-2021-10-29_08.09.42.hprof?dl=0

**Comment by cyberpwnn** [comment]
Sweet, I'll take a look at this later today, just downloaded it thanks!

**Comment by kireevm96** [comment]
There is a bug even if the card is regenerated

**Comment by Cenoic** [comment]
Hey! I've taken another look at this and it appears the mem-leak doesn't actually even stem from the Iris plugin itself.

The Jar itself is fine, however when you are on the generated world of Iris, that's another story.
The utilized Ram just keeps growing and is collected.

However when no player is alive obviously nothing is happening, thus the entire heap decays. And instantly starts to reform 
![image](https://user-images.githubusercontent.com/92695286/139537360-8e26bcbc-09a9-476a-9e8e-6bfabaf61662.png)

^^ This continues all the way up until the 12GB Cap then the server crashes due to 'out of memory' simply because someone is standing idle on the Iris world.

I'm not entirely sure if this is an issue with Iris, just the world seed, Paper, etc..
We're looking into this, if you have anything for us to try other than the obvious (listed below), let us know.

- Using Vanilla Jar
- Updating to newest Paper build
- Another world (On an EWG generated world, we did not see this issue, so yes, it's an issue this Iris World)
- This issue happens on all parts of the Iris World

--> I'm going to try to generate a new Iris World and see if it persists on a new seed. 
[If this persists after all of these checks, I will provide my Iris config in addition and see if that helps.]

**Comment by Cenoic** [comment]
Difference on Vanilla Jar - Instead of building slowly it instantly jumps to an extreme-

However so does it has not surpassed a usage of 8GB, though does appear to be growing.
However as this obviously does not resolve the issue, I will not investigate vanilla jar any further.
![image](https://user-images.githubusercontent.com/92695286/139538959-8360f193-06e2-4068-8900-e5622ccd6288.png)


However, I will say that I did try to run the vanilla jar on the EWG world and got the exact same results with the vanilla jar, where the excessive RAM usage and issues- were not previously, and even a completely separate pattern.
![image](https://user-images.githubusercontent.com/92695286/139539066-6cfc10c4-7c96-426c-a53d-b384270dba85.png)
![image](https://user-images.githubusercontent.com/92695286/139539127-cb9f4353-433b-4a6d-ba16-3a245fc7d538.png)


This being shown- no further investigation was lead into Vanilla Jar as obviously it's not really a plausible solution to the issue, but does showcase it's not simply a flaw in Paper when handling the world.

**I do care to note that this is on the original world causing the issue, we have not attempted a new Iris seed**
- And while previously the issue required a player to join and be on the Iris world in-order to appear, no user being connected was required with the Vanilla Jar.

**Comment by Cenoic** [comment]
** I've updated to the newest build of Paper -- No change. **

However, I did push this test further after acknowledging that the stacks would keep growing as before. (Got up to 4GB, however appeared to grow slower... I just chop this up to coincidence as the end result was the same. )

Instead of standing at spawn I instead flew around the map to check differences....

at -200, 70, 600 the stacks never really grew.
Though their size was still excessive for idle... They didn't become giant 12-16GB stacks I'd see on the main server. 
![image](https://user-images.githubusercontent.com/92695286/139540071-d575b6ba-0445-4750-a39d-6ac60895fba1.png)


--- After further investigation I previously thought this was an issue across the entire Iris world.
It appears completely random.

I will provide region files, positions, etc.

**Comment by Cenoic** [comment]
https://www.dropbox.com/s/5petqlgjt01bjig/Regions.zip?dl=0

-> x: 19, z: 104

Though other areas can cause issues, that area in particular has on every occasion tested.
[Our server has a spawn there- the EWG world had the same spawn, no issue.]

^^ I've removed it from the upload though.

**Comment by Cenoic** [comment]
Same issue on a freshly generated Iris world.

**Comment by dimactek96** [comment]
This error is relevant, there is a memory leak

**Comment by Cenoic** [comment]
Ofc there is. But their team says that 8-14GB memory is just normal Garbage Collection, lmfao. 

The worst part is that it's only certain biomes and areas that are issues.
If I stand over an ocean, I have no issues.

If I stand in the regions provided above, issues.

**Comment by Cenoic** [comment]
The worst part is that I put all this work into investigating and testing things to make their life easier and such a dire-issue is written off by their team. :/

**Comment by ghost** [comment]
We are here to help collect information to solve the problem. Blaming people doesn’t solve it. So It’s not written off by us. It’s just that the dev couldn’t reproduce it. You need to help him/us to reproduce it and/or provide further information.

**Comment by svdgoor** [comment]
Cyberpwn is the only one that can resolve issues such as this one as it's root lies deep within Iris, and the code isn't clear for the ones that haven't written it.
Cyberpwn has not written off this issue, neither have we.

**Comment by TH3N3WN00B** [comment]
Hey, just reading here and havent seen any of the dumps, but I read that you are using paper, while on the [Iris wiki](https://docs.volmit.com/iris/getting-started) it highly recommends using [Purpur](https://purpur.pl3x.net/downloads/), hope this helps :D

**Comment by svdgoor** [comment]
Purpur may slightly reduce default memory pressure, but won't be able to fix the iris-native memory leak unfortunately.

**Comment by dimactek96** [comment]
> Cyberpwn is the only one that can resolve issues such as this one as it's root lies deep within Iris, and the code isn't clear for the ones that haven't written it. Cyberpwn has not written off this issue, neither have we.

no server at 60+ online will use clean paper?

**Comment by svdgoor** [comment]
@dimactek96 Why did you reply to that message?
I'm not sure I understand what you're trying to say.

**Comment by dimactek96** [comment]
> @dimactek96 Why did you reply to that message? I'm not sure I understand what you're trying to say.

sorry, I clicked the wrong message, you need to click on 1 below

**Comment by TH3N3WN00B** [comment]
> Purpur may slightly reduce default memory pressure, but won't be able to fix the iris-native memory leak unfortunately.

Understood, just a mild idea that I had, hopefully this memory leak can be resolved

**Comment by Cenoic** [comment]
I'd like to apologize to the Iris team on behalf of us.

After more prolonged testing and investigation, this isn't even an issue with Iris.
It appears this stems from Vanilla 1.17 Minecraft Generation somewhere...

Epic World Gen (Because it uses much older generation and has never been actually updated to support 1.16+) does not have this issue. (Hence why when switching between the EWG world and Iris World, there was a real difference)

Thus, while on a EWG world- No issue. Iris / Vanilla World = Issue.
I hope to see this resolved in 1.18, though I don't think this is actually something that the Iris team has control of, and instead an issue that is better suited to be presented to Minecraft, as on pure vanilla- their generation causes a memory-leak.

**This is not to say that there isn't 2 separate memory-leaks, however I'm going to go with the idea that is unlikely and seeing as the evidence showcases that vanilla jar, spigot, and paper jar on a vanilla world all have a memory-leak issue on vanilla generation (and not EWG generation) this showcase provides evidence that Vanilla 1.17 Generation has a memory-leak**

I will leave it to the Iris Team to investigate on their own to see if there is also an issue with their code or simply an issue with 1.17 in general.

However, either way, we are stuck with Iris because the alternative of RWG / EWG is completely unappealing and if we used Vanilla, we'd have a memory leak anyways.

**Comment by svdgoor** [comment]
Hey!
Thanks for keeping an eye out on this and doing even more research!
Iris isn't perfect either and, while there mag be an issue in vanilla, there are probably multiple optimisations possible within iris as well.
I'll leave this open until either Mojang fixes it or Iris can somehow internally reduce it so that it doesn't become a problem (as fast).

**Comment by NextdoorPsycho** [comment]
says thank you- does not close issue lol
