### ISSUE TITLE
Repaint custom biomes

### ISSUE THREAD

**Issue by svdgoor** [VolmitSoftware/Iris#681]
### Adding, Removing, or Changing

Adding

### Type of Modification

I want to be able to have Iris reset all the custom biomes

### What are you trying to modify

The way I would implement this is by adding `/iris repaint` or `/iris resetbiomes` which would set all biomes to their custom Iris types in the entire world, as it would in the beginning. 

### Alternatives

If this could not be implemented I would have to find a way to manually set the biomes, and do it throughout the world.

The main reason for this is that sometimes the custom biomes are lost, for whatever reason.
Having this would allow people to fix those issues when they occur, instead of having permanent loss.

**Comment by NextdoorPsycho** [comment]
No, this is trying to fix a problem like a bandaid, instead of preventing the whole problem from happening to start with

**Comment by svdgoor** [comment]
@NextdoorPsycho it would fix the issue for people that already had this happen to them.

**Comment by Skizzles** [comment]
> No, this is trying to fix a problem like a bandaid, instead of preventing the whole problem from happening to start with

I have personally had mine reset 6 times now (just happened again today)

I agree it's a bandaid but PLEASE consider implementing it so existing worlds can fix their world.

**Comment by PaintsplattersMC** [comment]
agreed

**Comment by ghost** [comment]
I doubt that it’s doable (or in a reasonable timeframe) cause the biome colors can only be enabled before the world is generated. So preventing them to disappear is THE way to go. Rather than investing a huge amount of time in a bandaid fix that isn’t solving the actual problem at all.

**Comment by svdgoor** [comment]
Worldsdit can change biomes in the fly, don't see why iris wouldn't be able to do the same thing.

**Comment by NextdoorPsycho** [comment]
> @NextdoorPsycho it would fix the issue for people that already had this happen to them.

No it would not fix the issue. What this would do is ignore what's causing the problem and put something over it that a server owner would now need to micromanage, I would much rather just straight prevent them from breaking in the first place, Why you don't see it that way is beyond me.

> > No, this is trying to fix a problem like a bandaid, instead of preventing the whole problem from happening to start with
> 
> I have personally had mine reset 6 times now (just happened again today)
> 
> I agree it's a bandaid but PLEASE consider implementing it so existing worlds can fix their world.

Again, we will have a system that prevents it happening in the first place so we dont need to go down that road, and being that iris repaints in single coloum spaced going staright to bedrock, unless want to repaint it, block by block id mych rather just wix the problemto begin with

> I doubt that it’s doable (or in a reasonable timeframe) cause the biome colors can only be enabled before the world is generated. So preventing them to disappear is THE way to go. Rather than investing a huge amount of time in a bandaid fix that isn’t solving the actual problem at all.

Literally the only one who understands, If something is causing a problem like a really stinky odor, sure you can add air fresheners, and perfumes to make it smell nice, but you will eventually smell that bad smell again, the only way to really stop this from progressing it to not allow things to reset biome colors in the first place.

> Worldsdit can change biomes in the fly, don't see why iris wouldn't be able to do the same thing.


Not sure who you are arguing for, but worldedit can set vanilla biomes, we would need to get into worldedit and make them support non-vanilla biomes. ADDITIONALLY biome colors in datapacks need to be set on INIT, and chunkgen, there's no if's and's or but's its literally a limitation that we cant do something so instead of trying to find some jacked up way to make a biomecolor repaint itself, Preventing anything from touching the world just makes more sense
