### ISSUE TITLE
Iris generates objects at random heights

### ISSUE THREAD

**Issue by NotAShelf** [VolmitSoftware/Iris#775]
### Problem

1. Install Iris...
2. Generate your world (any method works, I used bukkit.yml)
3. Fly around your world, there'll be random objects such as trees and nether portals generated at Y=180 and above.

### Solution

n/a

### Minecraft Version

1.18

### Iris Version

2.0.3-1.18.2

### Log

https://mclo.gs/nxTvpVK

**Comment by NotAShelf** [comment]
update: it may not be just Y=180, it also generates some random trees right above the ocean

https://ss.notashelf.dev/‍‍​⁠‍⁠⁠⁠​‍​​​‌​ (click for the SS, couldn't upload an image to the message)

**Comment by svdgoor** [comment]
Caused by an occurrence we called something with shifting, which basically means something changed before placing the objects that makes iris think the height at those locations is actually off.

Are you sure you're on a stable server and haven't changed anything in the pack?
Have you tried a studio world, does it do the same?
Have you tried pregeneration?
Can you send a video of this behaviour, from creating the world to seeing the behaviour?

**Comment by NotAShelf** [comment]
> Are you sure you're on a stable server and haven't changed anything in the pack?

Fresh install of latest purpur (by latest, I mean literally `wget -O server.jar https://api.purpurmc.org/v2/purpur/1.18.2/latest/download `) with Iris v2.0.3, only Iris plugin is present. Obtained overworld by cloning it from github after downloading the server jar and placing Iris in the plugins folder.

> Have you tried a studio world, does it do the same?

Not yet, but I will try now.

> Have you tried pregeneration?

No, since this was on a local server hosted on my pc rather than my actual machine I did not want to pregenerate. Again, I will now.

> Can you send a video of this behaviour, from creating the world to seeing the behaviour?

Yes, will send tomorrow.

**Comment by konsheng** [comment]
![9HDWL29O3(AX~8@3RX(P25A](https://user-images.githubusercontent.com/75506674/160459350-70db394e-bfc6-46e9-99d4-2937d4e22aef.png)
The trees are all in the sky, please fix it quickly, this is a bug that seriously affects the experience, thank you.

**Comment by svdgoor** [comment]
Are there any trees/objects that float BELOW `256` or `192`?

**Comment by NotAShelf** [comment]
There are, around Y=180 is where they usually generate.
Sometimes they also generate right above the ocean .

**Comment by svdgoor** [comment]
I am unsure what causes this, and I know that this type of stuff is extremely hard to figure out because everything effects it, but I will try.

**Comment by NotAShelf** [comment]
doesn't seem to be present in the world generated by Rift (instead of bukkit.yml)

could we assume bukkit.yml is the root of the cause this time?

**Comment by svdgoor** [comment]
No. I think that this is caused by server instability which affects the concurrency of the streams we use to define a shit ton of different heights in the world for any given x,z location.
Better to pregen than to explore.
I failed to find the root cause in the code. Please try to pregen a world and then put it in place of the world you want to have it in (make sure to use the same seed, blah blah)
