### ISSUE TITLE
Iris does not manage the spawn of the mobs

### ISSUE THREAD

**Issue by plexium1** [VolmitSoftware/Iris#781]
### Problem

1. Install purpur (1.18.2)
2. Install Iris (2.0.3)
3. Install Overworld pack
4. Overwrite the main world with Iris (bukkit)
5. We observe that mobs spawn in the walls
6. Stop the server
7. Make changes in the overworld pack in the world files (e.g. replace all entities by pigs)
8. Restart the server
9. We observe that nothing changes, the classic mobs appear.

### Solution

Hello, after a lot of testing, I can confirm that it is not iris that manages the spawn of the monsters. They will appear as in vanilla even though they are activated in the Iris settings. 

I like the Iris spawn system and I would like to use it but I don't know why it doesn't work for me

Thanks for your attention

### Minecraft Version

1.18

### Iris Version

2.0.3

### Log

https://mclo.gs/wW8YIGJ

**Comment by XINGO0123** [comment]
![2022-04-13_16 11 01](https://user-images.githubusercontent.com/95913603/163336352-39d43c53-208e-4c96-92f6-eb57998ea7a9.png)
I think I meet a same problem

**Comment by NextdoorPsycho** [comment]
The mobs spawning in a cluster is not that iris cant manage mobs, its the faults in the energy system for spawning mobs to fill a "server" and there is only 1 place to spawn them and you are the only one on. 

For example if you are on a server with 50+ people the problem is always getting mobs because of mob farms etc... iris actively prevents this from happening or spawning mobs near players with farms. trying to evenly distribute the amount of mobs across the world. 

We'll look into improving this system
