### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by devspexx** [VolmitSoftware/Iris#880]
Hello I'm having issues with building the project. I have tried 2 times and I always get the exact same results. 

To build a project, I've used 2 commands (gradlew setup, gradlew iris). 

After when the build completed there was an error: (Task :specialSourceRemapObfuscate FAILED) Exception in thread "main" java.io.FileNotFoundException: C:\Users\spexx\.m2\repository\org\spigotmc\minecraft-server\1.19.1-R0.1-SNAPSHOT\minecraft-server-1.19.1-R0.1-SNAPSHOT-maps-mojang.txt (The system cannot find the path specified)"

Is there a way to fix this? I did type all the commands that are required, right?

Attachments:
![image](https://user-images.githubusercontent.com/46614224/187527168-2238cff5-ee8c-437f-8f47-ac05c480c704.png)

**Comment by ghost** [comment]
I’ll quote the dev
„ Compiling usually is designed for people that know what they’re doing and we have all the steps on GitHub if you are unable to get it to compile by following the steps I would encourage you to look up resources on how to compile plug-ins what do you need to do etc. I would encourage you to download it and test it from the github if you're a developer or just know how to, you’re welcome to crack it on certain cracking sites if you really just wanted a quick five minute test. But all in all I feel the get up is designed for people that know what they’re doing and the fact that we have instructions is already going above and beyond,

if you’re having issues compiling just try running build tools for a couple different versions at like 1.19 through 1.19.2 otherwise I’m not really going to help on this matter, but if you manage to buy crack or compile the jar we will help you either way“

**Comment by devspexx** [comment]
@Armin231 Yeah, I just figured it out 👍🏻

**Comment by different-name** [comment]
The following line in build.gradle should be updated according to your spigot jar version
`def spigotJarVersion = '1.19.1-R0.1-SNAPSHOT'`
