### ISSUE TITLE
Iris Detect multiverse on server

### ISSUE THREAD

**Issue by RePixelatedMC** [VolmitSoftware/Iris#947]
### Adding, Removing, or Changing

Adding

### Type of Modification

Multiverse  

### What are you trying to modify

is it possible to make a iris being able to detect a server running multiverse on it? so it could like tell the user that its incompatible and redirect them to the docs / a new docs page which information on why multiverse is incompatible and that the should use /iris create jadada you get the story

### Alternatives

Cry and give ppl emotional support for there corrupt worlds cause the didnt read the docs

**Comment by svdgoor** [comment]
Please look up the national suicide prevention hotline for your country.

We could probably add this, but Multiverse is so extremely good at fucking up your worlds that when you install it it's likely already too late for existing Iris worlds.
For NEW Iris worlds though, we could likely implement something where if MV is on the server, Iris just does not boot (again, unless it has worlds in the server already, in which case it should def. startup because otherwise the chance of worlds breaking is just 100%).
We are not allowed to shutdown the server if MV is installed unfortunately, due to SpigotMC requirements.

**Comment by svdgoor** [comment]
Think this isn't a great idea. I like it when people join the discord and this is a great way to get them in there :)
