### ISSUE TITLE
'/iris pregen' command, will not pregenerate stronghold

### ISSUE THREAD

**Issue by Illusionika** [VolmitSoftware/Iris#958]
### Problem

1. Install purpur-1.19.3-1912, Iris-2.3.14-1.19.3
2. Create the iris world, use '/iris pregen' to pregenerate the map
3. Use /iris goto structure structure=stronghold' to find stronghold
4. There are all Stones, no stronghold
But if you do not use /iris pregen, but generate naturally, the same coordinates have stronghold

Use /iris pregen
![R](https://user-images.githubusercontent.com/46653839/218607900-be608473-afcd-4e67-bd62-043c7f21de89.png)

Do not use /iris pregen
![NOT](https://user-images.githubusercontent.com/46653839/218607941-581e15c7-91cf-4e02-a6b1-882520fad113.png)

### Solution

pregenerate stronghold

### Minecraft Version

1.19

### Iris Version

2.3.14

### Log

none

**Comment by svdgoor** [comment]
I'm not sure why this was closed. The issue remains.

**Comment by Svenprogamer** [comment]
Hello!

I also had this issue but if found a fix!

1. Delete the iris.jar from the plugin list and restart your server (You need to do this so that you can't throw an eye of ender anymore)
2. now add the iris.jar to your plugin list and start the server again
3. when you are in your iris world now if everything did go right you can't throw an eye of ender at all (instead of going to the wrong location as mentioned above)
4. now download this plugin: https://drive.google.com/file/d/1XlxnMyx4lWfXbDWqJqWX346AjNxv1-Yz/view?usp=sharing 
5. when you have restarted your server you can set your own waypoints with /endereye add (name) this is where you want to add your strongholds in your world.
6. if you forgot all the location of the ender eyes you can create a copy of your world with /iris studio open overworld (your world seed use /seed)
7. now you need to go in your world and find all the stronghold locations with /iris find structure structure=stronghold this will take some time
8. write all the coordinates of the strongholds down and add those coordinates to the eye of ender locations (make sure you have use-stronghold-location: false)
9. restart your server
10. if you have multiworld installed the endereye changer plugin will be loaded before the iris wolrd will be loaded you can fix this in a few ways 1. install the PlugmanX and startupcommands plugins to your server and fill in the startupcommands config plugman reload endereyechanger 2. use the /reload command
11.  Now everything should work

i am gonna try to make a /endereyechanger reload command so that you dont have to install PlugmanX

if you have questions or errors add Sven#8036 on discord or ping me in the volmit discord server.

**Comment by NextdoorPsycho** [comment]
If you are still having this issue, @Svenprogamer you can even PR your fix and ill be glad to merge it!
