### ISSUE TITLE
Broken "center" parameter in pregeneration process - 2 bugs

### ISSUE THREAD

**Issue by lukipukix** [VolmitSoftware/Iris#978]
### Problem

I just discovered that setting "center=10,10" in pregeneration process is actually moving coordinates (+/- ofc) from 0,0 to 5120,5120. **one unit = 512 block**

Another bug with this thing: **second position of "center" parameter in pregeneration process doesn't change anything at all**. (btw this is most important thing for me xd)

Image below shows left upper corner (first) and right down corner (second) coordinates with different center positions on pregenerated maps with radius=1000. I checked this by moving world to singleplayer and entering on it with Xaero's World Map mod installed so I could see rendered terrain.

### Minecraft Version

1.19.X
### Iris Version

Iris-2.4.2-1.19.3

### Log

https://mclo.gs/wZMyFhT#L505

![image](https://user-images.githubusercontent.com/98988597/224721807-a0ced49e-aee3-48ae-b84d-9e51b2bfcf0f.png)

**Comment by svdgoor** [comment]
I have investigated this and noticed that 
a) the center parameter does in fact work. I specified `/ir pregen start 1024 center=10000,10000` which does generate region files way out from the center:
![image](https://github.com/VolmitSoftware/Iris/assets/65736624/5a7c8294-645d-4896-aa3a-0240e097ce51)
b) As you can see in that same image, the region files are generated at around `10000`. This, however, is incorrect. The reason this is incorrect is that it should be `10k/512≈20` (the size of a region), so we would expect region files with numbers around that instead of the numbers we're seeing.
So the effect we notice is that the center is scaled by a factor 512. This is the only bug I can find.

I have written a fix for this issue, and you will see the PR mention this issue below here in a bit.

Hopefully this is sufficient information to help you get on. If you want a compiled version of the Jar with this change you can either do it yourself or reach out to me on Discord.

**Comment by svdgoor** [comment]
Oh on a final note: You can also divide the location you want by 512 and then enter that number in the center parameter instead.
